### ISSUE TITLE
How to install on glpi 10.0.2 

### ISSUE THREAD

**Issue by F4izal** [cconard96/glpi-stab-plugin#1]
Thanks for create this plungin is very good.
Im soory for my english is bad.

I try install this plugin stab on server, installation succucesfully but not work on menu follow up and task.

Can you help me please for my problem.

**Comment by cconard96** [comment]
I tested this plugin on the latest GLPI 10 RC release and it is working for me.
Please verify that the plugin shows that it is enabled instead of just installed.

Also, can you open the browser console (F12 key and then Console tab) and see if there are any errors when you go to a ticket and try clicking Task or Followup in the menu, or opening the edit form of an existing Task or Followup?

**Comment by F4izal** [comment]
Ah i see ... Im soory this is my fault plungin working great on glpi 10.0.0 rc2 .. thanks for help. 

I closed for issues.
